# Generated by Django 5.2.6 on 2025-11-09 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoAcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("matematica", "Matemática"),
                            ("portugues", "Língua Portuguesa"),
                            ("ciencias", "Ciências"),
                            ("historia", "História"),
                            ("geografia", "Geografia"),
                            ("artes", "Artes"),
                            ("educacao-fisica", "Educação Física"),
                            ("multidisciplinar", "Multidisciplinar"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True, max_length=500)),
                ("objetivos", models.TextField()),
                ("estrategias", models.TextField()),
                ("recursos", models.TextField(blank=True)),
                ("avaliacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("rascunho", models.BooleanField(default=False)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
