# Generated by Django 5.2.6 on 2025-11-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_profile_disciplina_principal_profile_escola_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='disciplina_principal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='serie_ano',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telefone',
        ),
    ]
