# Generated by Django 5.2.6 on 2025-11-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_remove_profile_disciplina_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('progresso', models.IntegerField(default=0)),
                ('descricao', models.TextField(blank=True)),
                ('objetivos', models.TextField(blank=True)),
                ('estrategias', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True)),
                ('avaliacao', models.TextField(blank=True)),
                ('plano_gerado', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
